##Transform the dataframe from the run_analysis.R to generate the codebook

hdactivity <- as.data.set(hdactivity, col.names = hdactivity, stringasFactors = FALSE)
hdactivity <- within(hdactivity,{
        description(Volunteer) <- "Volunteer number who executed the activity"
        description(Activity) <- "Task perfomed"
        description(tBodyAccmeanX) <- "Body Acceleration time signal mean X - axis"
        description(tBodyAccmeanY) <- "Body Acceleration time signal mean Y - axis"
        description(tBodyAccmeanZ) <- "Body Acceleration time signal mean Z - axis"
        description(tBodyAccstdX) <- "Body Acceleration time signal standard deviation X - axis"
        description(tBodyAccstdY) <- "Body Acceleration time signal standard deviation Y - axis"
        description(tBodyAccstdZ) <- "Body Acceleration time signal standard deviation Z - axis"
        description(tGravityAccmeanX) <- "Gravity Acceleration time signal mean X - axis"
        description(tGravityAccmeanY) <- "Gravity Acceleration time signal mean Y - axis"
        description(tGravityAccmeanZ) <- "Gravity Acceleration time signal mean Z - axis"
        description(tGravityAccstdX) <- "Gravity Acceleration time signal standard deviation X - axis"
        description(tGravityAccstdY) <- "Gravity Acceleration time signal standard deviation Y - axis"
        description(tGravityAccstdZ) <- "Gravity Acceleration time signal standard deviation Z - axis"
        description(tBodyAccJerkmeanX) <- "Body Acceleration Jerk time signal mean X - axis"
        description(tBodyAccJerkmeanY) <- "Body Acceleration Jerk time signal mean Y - axis"
        description(tBodyAccJerkmeanZ) <- "Body Acceleration Jerk time signal mean Z - axis"
        description(tBodyAccJerkstdX) <- "Body Acceleration Jerk time signal standard deviation X - axis"
        description(tBodyAccJerkstdY) <- "Body Acceleration Jerk time signal standard deviation Y - axis"
        description(tBodyAccJerkstdZ) <- "Body Acceleration Jerk time signal standard deviation Z - axis"
        description(tBodyGyromeanX) <- " Body Gyroscope time signal mean X - axis"
        description(tBodyGyromeanY) <- "Body Gyroscope time signal mean Y - axis"
        description(tBodyGyromeanZ) <- "Body Gyroscope time signal mean Z - axis"
        description(tBodyGyrostdX) <- "Body Gyroscope time signal standard deviation X - axis"
        description(tBodyGyrostdY) <- "Body Gyroscope time signal standard deviation Y - axis"
        description(tBodyGyrostdZ) <- "Body Gyroscope time signal standard deviation Z - axis"
        description(tBodyGyroJerkmeanX) <- "Body Gyroscope Jerk time signal mean X - axis"
        description(tBodyGyroJerkmeanY) <- "Body Gyroscope Jerk time signal mean Y - axis"
        description(tBodyGyroJerkmeanZ) <- "Body Gyroscope Jerk time signal mean Z - axis"
        description(tBodyGyroJerkstdX) <- "Body Gyroscope Jerk time signal standard deviation X - axis"
        description(tBodyGyroJerkstdY) <- "Body Gyroscope Jerk time signal standard deviation Y - axis"
        description(tBodyGyroJerkstdZ) <- "Body Gyroscope Jerk time signal standard deviation Z - axis"
        description(tBodyAccMagmean) <- "Body Acceleration Magnitude time signal mean"
        description(tBodyAccMagstd) <- "Body Acceleration Magnitude time signal standard deviation"
        description(tGravityAccMagmean) <- "Gravity Acceleration Magnitude time signal mean"
        description(tGravityAccMagstd) <- "Gravity Acceleration Magnitude time signal standard deviation"
        description(tBodyAccJerkMagmean) <- "Body Acceleration Jerk Magnitude time signal mean"
        description(tBodyAccJerkMagstd) <- "Body Acceleration Jerk Magnitude time signal standard deviation"
        description(tBodyGyroMagmean) <- "Body Gyroscope Magnitude time signal mean"
        description(tBodyGyroMagstd) <- "Body Gyroscope Magnitude time signal standard deviation"
        description(tBodyGyroJerkMagmean) <- "Body Gyroscope Jerk Magnitude time signal mean"
        description(tBodyGyroJerkMagstd) <- "Body Gyroscope Jerk Magnitude time signal standard deviation"
        description(fBodyAccmeanX) <- "Body Acceleration frequency signal mean X - axis"
        description(fBodyAccmeanY) <- "Body Acceleration frequency signal mean Y - axis"
        description(fBodyAccmeanZ) <- "Body Acceleration frequency signal mean Z - axis"
        description(fBodyAccstdX) <- "Body Acceleration frequency signal standard deviation X - axis"
        description(fBodyAccstdY) <- "Body Acceleration frequency signal standard deviation Y - axis"
        description(fBodyAccstdZ) <- "Body Acceleration frequency signal standard deviation Z - axis"
        description(fBodyAccJerkmeanX) <- "Body Acceleration Jerk frequency signal mean X - axis"
        description(fBodyAccJerkmeanY) <- "Body Acceleration Jerk frequency signal mean Y - axis"
        description(fBodyAccJerkmeanZ) <- "Body Acceleration Jerk frequency signal mean Z - axis"
        description(fBodyAccJerkstdX) <- "Body Acceleration Jerk frequency signal standard deviation X - axis"
        description(fBodyAccJerkstdY) <- "Body Acceleration Jerk frequency signal standard deviation Y - axis"
        description(fBodyAccJerkstdZ) <- "Body Acceleration Jerk frequency signal standard deviation Z - axis"
        description(fBodyGyromeanX) <- "Body Gyroscope frequency signal mean X - axis"
        description(fBodyGyromeanY) <- "Body Gyroscope frequency signal mean Y - axis"
        description(fBodyGyromeanZ) <- "Body Gyroscope frequency signal mean Z - axis"
        description(fBodyGyrostdX) <- "Body Gyroscope frequency signal standard deviation X - axis"
        description(fBodyGyrostdY) <- "Body Gyroscope frequency signal standard deviation Y - axis"
        description(fBodyGyrostdZ) <- "Body Gyroscope frequency signal standard deviation Z - axis"
        description(fBodyAccMagmean) <- "Body Acceleration Magnitude frequency signal mean"
        description(fBodyAccMagstd) <- "Body Acceleration Magnitude frequency signal standard deviation"
        description(fBodyBodyAccJerkMagmean) <- "Body Acceleration Jerk Magnitude frequency signal mean"
        description(fBodyBodyAccJerkMagstd) <- "Body Acceleration Jerk Magnitude frequency signal standard deviation"
        description(fBodyBodyGyroMagmean) <- "Body Gyroscope  Magnitude frequency signal mean"
        description(fBodyBodyGyroMagstd) <- "Body Gyroscope  Magnitude frequency signal standard deviation"
        description(fBodyBodyGyroJerkMagmean) <- "Body Gyroscope Jerk Magnitude frequency signal mean"
        description(fBodyBodyGyroJerkMagstd) <- "Body Gyroscope Jerk Magnitude frequency signal standard deviation"
        })
codebook(hdactivity)
Write(codebook(hdactivity),file="humandata-cdbk.txt") 
